name: Post PR Comment

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - name: Post comment to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request?.number || context.payload.workflow_run?.pull_requests?.[0]?.number;

            if (!pr) {
              core.setFailed('❌ Could not determine PR number.');
              return;
            }

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr,
              body: `### ✅ CI Results:\n${{ inputs.message }}`
            });
