name: PR to main

on:
  pull_request:
    branches: [main, dev]

jobs:
  ####################################
  # Job 1: Code Quality Checks
  ####################################
  code-checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run ESLint
        run: npx eslint .

      - name: Run PMD for Apex
        run: |
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.55.0/pmd-bin-6.55.0.zip
          unzip pmd-bin-6.55.0.zip
          ./pmd-bin-6.55.0/bin/run.sh pmd -d force-app -R category/apex/design.xml -f text

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npm install -g sonarqube-scanner
          sonar-scanner \
            -Dsonar.projectKey=raj-patel-149_github_Actions \
            -Dsonar.organization=raj-patel-149 \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${SONAR_TOKEN}

  deploy-to-qa:
    name: Deploy to Salesforce QA
    runs-on: ubuntu-latest
    needs: code-checks

    steps:
      - name: Checkout code (last 2 commits only)
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli
          sf --version || true

      - name: Create JWT Key File
        run: echo "${{ secrets.SF_JWT_KEY }}" > server.key

      - name: Authenticate to Salesforce
        run: |
          echo "Logging in with JWT..."
          if ! sf org login jwt \
            --client-id ${{ secrets.SF_CLIENT_ID }} \
            --jwt-key-file server.key \
            --username ${{ secrets.SF_USERNAME_QA }} \
            --alias QA \
            --instance-url https://login.salesforce.com; then
            echo "sf CLI failed, falling back to sfdx..."
            sfdx auth:jwt:grant \
              --clientid ${{ secrets.SF_CLIENT_ID }} \
              --jwtkeyfile server.key \
              --username ${{ secrets.SF_USERNAME_QA }} \
              --instanceurl https://login.salesforce.com \
              --setalias QA
          fi

      - name: Detect changed component folders
        id: changes
        run: |
          echo "Changed folders:"
          git diff --name-only HEAD^ HEAD | grep "^force-app" | cut -d'/' -f1-5 | sort -u > changed-folders.txt || true
          cat changed-folders.txt

      - name: Deploy changed components
        run: |
          if [ -s changed-folders.txt ]; then
            echo "Deploying changed folders..."
            while read folder; do
              echo "Deploying $folder"
              sf project deploy start \
                --source-dir "$folder" \
                --target-org QA \
                --ignore-conflicts \
                --wait 10
            done < changed-folders.txt

          else
            echo "No deployable changes found. Skipping deployment."
          fi

      - name: Run Apex Tests and Check Coverage
        run: |
          echo "Running all Apex tests..."
          sf apex run test \
            --target-org QA \
            --test-level RunLocalTests \
            --output-dir test-results \
            --result-format json \
            --wait 10

          echo "Extracting code coverage..."
          coverage=$(jq '[.result.coverage.coverage[].numLocationsCovered] | add / ([.result.coverage.coverage[].numLocations] | add) * 100' test-results/test-result.json)
          echo "Code Coverage: $coverage%"

          if (( $(echo "$coverage < 75" | bc -l) )); then
            echo "❌ Code coverage is below 75%. Failing the job."
            exit 1
          else
            echo "✅ Code coverage is 75% or higher."
          fi
