name: Salesforce CI/CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ####################################
  # Job 1: Code Quality Checks
  ####################################
  code-checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Run ESLint
        run: npx eslint .

      - name: Run PMD for Apex
        run: |
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.55.0/pmd-bin-6.55.0.zip
          unzip pmd-bin-6.55.0.zip
          ./pmd-bin-6.55.0/bin/run.sh pmd -d force-app -R category/apex/design.xml -f text

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npm install -g sonarqube-scanner
          sonar-scanner \
            -Dsonar.projectKey=raj-patel-149_github_Actions \
            -Dsonar.organization=raj-patel-149 \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${SONAR_TOKEN}

  ####################################
  # Job 2: Apex Test & Deploy to QA
  ####################################
  test-coverage:
    name: Apex Test & Deploy to QA
    runs-on: ubuntu-latest
    needs: code-checks
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Salesforce CLI (v2)
        run: |
          npm install --global @salesforce/cli
          echo "Salesforce CLI version:"
          sfdx --version || true
          echo "SF CLI version:"
          sf --version || true

      - name: Create JWT Key File
        run: echo "${{ secrets.SF_JWT_KEY }}" > server.key

      - name: Authenticate to Salesforce (fallback included)
        run: |
          echo "Trying sf CLI JWT login..."
          if ! sf org login jwt \
            --client-id ${{ secrets.SF_CLIENT_ID }} \
            --jwt-key-file server.key \
            --username ${{ secrets.SF_USERNAME_QA }} \
            --alias QA \
            --instance-url https://login.salesforce.com; then
            echo "sf CLI failed, falling back to sfdx..."
            sfdx auth:jwt:grant \
              --clientid ${{ secrets.SF_CLIENT_ID }} \
              --jwtkeyfile server.key \
              --username ${{ secrets.SF_USERNAME_QA }} \
              --instanceurl https://login.salesforce.com \
              --setalias QA
          fi

      - name: Validate Deployment & Run Tests
        run: |
          sf project deploy validate \
            --source-dir force-app \
            --test-level RunAllTestsInOrg \
            --target-org QA \
            --wait 10 \
